spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/data_service?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useAffectedRows=true
    username: root
    password: 123456

jst:
  api.url: https://c.jushuitan.com/api/open
  partnerId:
  token:
  partnerKey: