server:
  port: 8080
spring:
  main.allow-bean-definition-overriding: true
  application.name: http-workflow-temporal
  # temporal specific configs
  temporal:
    namespace: data-center-dev
    connection.target: 172.16.202.220:30917
    workersAutoDiscovery:
      packages: cn.sliew.http.workflow.temporal.workflow

# specific for samples
samples:
  data:
    language: english